# Generated by Django 5.0.4 on 2024-04-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author'),
        ('message', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
